[project]
name = "uv-light"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.*",
    "pandas==2.*",
    "pyarrow==18.*",
    "pytest>=8.3.3",
]
